### ISSUE TITLE
logrotation_size : What is the unit ?

### ISSUE THREAD

**Issue by jk-12345** [ilyautkin/logRotation#1]
Hi,

I have installed this plugin to my Modx website and I would like to know what is the unit associate to logrotation_size ?
- B
- kB
- MB ?

Thanks

**Comment by ilyautkin** [comment]
Hi, unit is `bytes` - plugin used function [filesize()](https://www.php.net/manual/en/function.filesize.php)

<a href="https://ilyaut.ru/cloud/235GX7.png" target="_blank"><img src="https://ilyaut.ru/x180/235GX7.png" class="fancybox"></a>
